name: 'Deploy App to S3'

#on: [push] # toutes les branches
# ou bien
on:
  push:
    branches:
      - main # uniquement sur la branche main

 - name: List directory
       run: |
         ls -la
     - name: create new file
       run: |
         touch newfile.txt
     - name: List directory again
       run: |
         ls -la